var listedephrases=[]
const vener=[
    "Grrr !",
"Aaargh !",
"Pfff !",
"Meh !",
"Mouais !",
"Tss !",
"Humf !",
"Nan mais sérieux ?!",
"Pfff, n'importe quoi !",
"Tchh !",
"M'enfin !",
"Rah !",
"Pfff, j'en ai marre !",
"Franchement, c'est abusé !",
"Pff, laisse tomber !",
"Grrr, ça m'énerve !",
"Trop énervant !",
"Mais quelle galère !",
"Pfff, c'est même pas drôle !",
"C'est insupportable !",
"Mais qu'est-ce que tu racontes ?!",
"C'est n'importe quoi !",
"Grrr, je suis trop énervée !",
"Pfff, ça me fatigue !",
"Mais tu plaisantes ?!",
"Je n'en peux plus !",
"Rah, ça me saoule !",
"C'est vraiment exaspérant !",
"Pfff, j'ai la rage !",
"Tchh, je suis trop vénère !",
    "CHEH!",
    "Tu dead ça, baby",
    "Vazy, oublie-moi",
    "Pfffffff",
    "T'parles avec qqun d'autre ou quoi",
    "T'es avec qui là",
    "jpp",
    "🖕",
    "ksss",
    "Si tu dis rien, c'est pas la peine de rentrer 😡",
    "C'pas comme ça que tu vas me regagner",
    "J'en ai marre d'attendre ! 😡",
"Qu'est-ce que ça prend autant de temps ? 💀",
"Je ne peux plus patienter ! 😤",
"Je suis à bout de patience ! 😤",
"J'ai la flemme d'attendre plus longtemps 💀",
"C'est quand qu'on bouge enfin ?",
"J'ai pas de temps à perdre ! 😡",
"J'ai envie que ça se termine vite ! 😡",
"Je suis fatiguée 💀",
"Je suis pressée d'en finir avec ça 😤",
"C'est trop long, j'ai besoin d'action maintenant ! 💀",
"Je ne supporte plus d'attendre sans rien faire 😡",
"Je suis en train de bouillir 😡!",
"🤬",
"J'ai hâte que ça se termine ! 🥱",
"Je suis épuisée d'attendre sans raison 🥱",
"Je n'ai plus de patience à donner 😤",
"J'ai besoin que ça se passe maintenant ! 💀",
"J'en ai marre d'attendre sans savoir quand ça finira 🤬",
"J'ai l'impression que ça n'avance pas du tout ! 😡",
"J'ai pas de temps à perdre avec ça 💩",
"J'ai les nerfs à fleur de peau ! 😡",
"Je suis au bord de l'explosion ! 😡",
"C'est pas possible d'attendre autant ! 💀",
"Je ne peux plus supporter cette attente interminable ! 🖕",
"Je veux que ça bouge enfin! 💀",
"Je suis lasse d'attendre pour rien 🥱",
"J'ai besoin que ça se débloque !",
"🤬"
]
const reponses=["Je pense qu'à toi, bébé",
"Mon cœur bat la chamade quand je te vois",
"Tu me manques, c'est pas humain",
"Je t'ai préparé un truc de fou pour ce soir",
"J'suis trop heureuse de t'avoir dans ma life",
"T'es la plus belle chose qui me soit arrivée",
"J'aimerais trop t'avoir dans mes bras là tout de suite",
"Tu es le soleil qui illumine mes journées",
"J'ai trop hâte de te voir ce soir, bébé",
"Quand je pense à toi, j'ai le coeur qui palpite",
"Je suis prête à tout pour passer du temps avec toi aujourd'hui",
"T'es la flamme qui brûle mon cœur",
"Avec toi, j'ai l'impression de pouvoir tout accomplir",
"J'ai besoin de ta présence pour me sentir heureuse et épanouie",
"T'es mon petit bébé, j't'aime tellement fort",
"Chaque moment passé avec toi est une bénédiction",
"J'adore quand tu me regardes avec tes yeux de braise",
"J'aime tellement sentir ta main dans la mienne",
"T'es tellement sexy que tu me fais perdre la tête",
"T'es le/la seul(e) qui puisse me faire rire même quand j'suis pas d'humeur",
"Je suis trop fière de t'avoir à mes côtés chaque jour",
"J'ai hâte de partager tous mes rêves avec toi",
"T'es la personne la plus incroyable de la planète, bébé",
"Je rêve de toi toutes les nuits, mon amour",
"T'es mon reuf/ma reusta et mon amoureux en même temps",
"T'es ma lumière dans la nuit, bébé",
"Je suis trop love de toi, j'peux pas imaginer ma vie sans toi",
"Y a que toi qui peut me faire oublier mes soucis",
"Je t'aime plus que tout, et j'ferai tout pour toi",
"Mon but dans la vie, c'est de te rendre heureux, bébé"]
const niveaux=[
    {nom:"Année-Lumière",
    prota1:"img/han.png",
    prota2: "img/leia.png",
    phrases:["Notre amour est aussi distant que les étoiles, mais tout aussi brillant à travers les années-lumière",
"Tu es à des années-lumière de moi, mais je ressens ta présence dans mon coeur",
"Notre amour traverse les années-lumière et les galaxies pour être ensemble",
"Même si je suis à des années-lumière de toi, mon amour pour toi brille plus fort que toutes les étoiles",
"Nos coeurs sont liés pour l'éternité, malgré les années-lumière qui nous séparent",
"Ton amour m'éclaire comme une étoile dans la nuit, à des années-lumière de tout ce qui est banal",
"Je t'aimerai à travers les années-lumière, jusqu'à ce que la fin du temps nous réunisse",
"Tu es la lumière de ma vie, même à des années-lumière de distance",
"Notre amour est un phare dans l'obscurité, brillant à travers les années-lumière",
"Je t'aime au-delà des frontières de l'espace et du temps, à travers des années-lumière et des éons",
"Notre amour est plus grand que l'univers, brillant à travers les années-lumière pour toujours",
"Je t'aime à travers les galaxies, à travers les années-lumière, jusqu'à l'infini",
"Notre amour est comme un rayon de lumière, traversant les années-lumière pour nous rejoindre",
"Même à des années-lumière de distance, je sens ton amour briller dans mon coeur",
"Notre amour est une constellation brillante, visible à travers les années-lumière",
"Ton amour est une étoile qui brille dans l'univers, même à des années-lumière de moi",
"Notre amour brille comme une supernova, même à des années-lumière de distance",
"Notre amour est un phénomène cosmique, traversant les années-lumière pour nous unir",
"Ton amour est la lueur d'espoir dans mon coeur, même à des années-lumière de distance",
"Notre amour est une comète qui traverse l'univers, brillant à travers les années-lumière",
"Ton amour est une planète lointaine, mais je suis prêt à voyager des années-lumière pour te rejoindre",
"Notre amour brille plus fort que n'importe quelle étoile, à travers des années-lumière d'espace et de temps",
"Je suis prêt à parcourir des années-lumière pour être avec toi, mon amour"]},
{nom:"Avant-Jour",
prota1:"img/cendrillon.png",
prota2:"img/princecharmant.png",
phrases:["L'amour est comme l'aube, il annonce une nouvelle journée remplie d'espoir et de promesses",
"L'amour est cette étincelle qui brille juste avant l'aube, réchauffant nos coeurs et illuminant notre chemin",
"L'amour est le début d'un nouveau jour, un jour rempli de possibilités et d'aventures",
"Notre amour est comme l'aube, doux et calme, remplissant notre coeur de paix et de sérénité",
"Le lever du soleil est le moment le plus magique de la journée, tout comme l'amour est le moment le plus magique de la vie",
"L'amour est comme l'aube, il éclaire notre vie et donne un sens à notre existence",
"L'amour est cette lueur d'espoir qui apparaît juste avant l'aube, nous rappelant que chaque jour est une nouvelle chance",
"Notre amour est comme l'aube, remplissant notre vie de lumière et de chaleur",
"L'amour est la promesse d'un nouveau jour, rempli d'aventure et de bonheur",
"L'amour est comme l'aube, il apporte la lumière dans nos vies et nous guide vers un nouvel horizon",
"Notre amour est comme l'aube, un moment magique où tout est possible",
"L'amour est cette lumière qui apparaît juste avant l'aube, nous réchauffant le coeur et nous remplissant d'espoir",
"L'amour est comme l'aube, il nous rappelle que chaque jour est une nouvelle chance de faire des choses extraordinaires",
"Notre amour est comme l'aube, un moment de grâce et de beauté qui éclaire notre vie",
"L'amour est cette douceur que l'on ressent juste avant l'aube, une promesse de bonheur à venir",
"L'amour est comme l'aube, il éclaire notre vie et nous guide vers de nouveaux horizons",
"Notre amour est comme l'aube, un moment magique où tout est possible, où tout peut changer",
"L'amour est cette lumière qui brille juste avant l'aube, remplissant notre vie de beauté et de merveilles",
"L'amour est comme l'aube, un moment de grâce et de beauté qui annonce une nouvelle journée",
"Notre amour est comme l'aube, un moment de paix et de sérénité qui remplit notre vie de bonheur",
"L'amour est cette lumière qui brille dans l'obscurité, annonçant une nouvelle journée remplie d'espoir"]},
{nom:"Dare-Dare",
prota1:"img/maya.png",
prota2:"img/willy.png",
phrases:["Lorsque nous sommes amoureux, nous fonçons dare-dare vers l'avenir main dans la main, prêts à affronter tous les défis",
"L'amour nous pousse à agir dare-dare, sans hésiter, car nous savons que chaque moment compte",
"Lorsque nous sommes amoureux, nous avons l'impression que tout doit se faire dare-dare, car chaque instant sans l'autre nous paraît interminable",
"L'amour nous donne des ailes pour avancer dare-dare vers notre avenir commun",
"Lorsque nous sommes amoureux, nous sommes prêts à tout pour notre bien-aimé(e), même si cela signifie agir dare-dare",
"L'amour nous fait courir dare-dare vers l'autre, car il est notre source de bonheur",
"Lorsque nous sommes amoureux, chaque seconde sans l'autre nous paraît insupportable, nous incitant à agir dare-dare pour être ensemble",
"L'amour nous pousse à foncer dare-dare vers l'avenir, main dans la main, pour construire notre vie ensemble",
"Lorsque nous sommes amoureux, nous avons envie de tout faire dare-dare, car chaque moment passé ensemble est précieux",
"L'amour nous fait avancer dare-dare vers l'autre, car il est notre raison de vivre",
"Lorsque nous sommes amoureux, nous sommes prêts à braver tous les obstacles et à agir dare-dare pour être avec celui ou celle que nous aimons",
"L'amour nous donne l'énergie nécessaire pour avancer dare-dare vers notre avenir commun, main dans la main",
"Lorsque nous sommes amoureux, nous avons envie de tout partager avec notre bien-aimé(e), sans perdre une minute, car le temps passe dare-dare",
"L'amour nous fait avancer dare-dare vers notre destinée, car nous savons que rien n'est plus important que notre relation",
"Lorsque nous sommes amoureux, nous avons l'impression que rien ne peut nous arrêter, que tout doit se faire dare-dare, car chaque moment compte",
"L'amour nous donne le courage d'agir dare-dare pour être avec l'autre, même si cela signifie prendre des risques",
"Lorsque nous sommes amoureux, nous sommes prêts à tout pour être ensemble, sans attendre, sans hésiter, dare-dare",
"L'amour nous donne des ailes pour foncer dare-dare vers notre avenir commun, rempli de bonheur et d'amour"]},
{nom:"dejavu",
prota1:"img/neo.png",
prota2:"img/trinity.png",
phrases:["Notre amour était déjà écrit quelque part, comme si nous nous étions déjà vus dans une vie antérieure",
"Je te regarde et j'ai l'impression de t'avoir déjà vu quelque part, dans une autre vie peut-être, car notre amour semble déjà existé depuis toujours",
"Notre amour est comme un déjà-vu, comme si nous avions déjà connu cette intensité et cette complicité dans une autre vie",
"Lorsque je suis avec toi, j'ai l'impression de revivre un déjà-vu, comme si je t'avais déjà aimé dans une vie antérieure",
"Notre amour est comme une évidence, comme un déjà-vu, comme si nous avions toujours été destinés à nous rencontrer",
"Je suis tombée amoureuse de toi dès notre première rencontre, comme si j'avais déjà vécu ce moment auparavant, un déjà-vu puissant et merveilleux",
"Notre amour est comme un déjà-vu, comme si nous avions déjà connu cette passion et cette connexion dans une autre vie",
"Je te connais à peine et pourtant je ressens déjà une connexion profonde, comme si notre amour était déjà-vu",
"Lorsque je suis avec toi, j'ai l'impression d'avoir déjà vécu ces moments, comme si notre amour était déjà inscrit quelque part",
"Notre amour est comme un déjà-vu, comme si nous nous étions déjà aimés dans une autre vie, une certitude qui m'emplit de joie",
"Je te regarde et j'ai l'impression de déjà te connaître depuis toujours, comme si notre amour était déjà-vu",
"Notre amour est comme un déjà-vu, comme si nous avions déjà connu cette alchimie parfaite dans une autre vie",
"Je suis tombée amoureuse de toi instantanément, comme si notre amour était déjà-vu, une évidence qui ne pouvait être ignorée",
"Notre amour est comme un déjà-vu, comme si nous avions déjà connu cette connexion profonde et inexplicable",
"Je t'aime comme si je t'avais déjà aimé dans une vie antérieure, un déjà-vu qui me remplit de bonheur",
"Notre amour est comme un déjà-vu, comme si nous nous étions déjà promis de nous aimer pour toujours",
"Je te regarde et j'ai l'impression de t'avoir déjà connu dans une autre vie, comme si notre amour était déjà-vu",
"Notre amour est comme un déjà-vu, comme si nous avions déjà connu cette fusion parfaite dans une autre vie"]},
{nom:"Hivernage",
prota1:"img/elsa.png",
prota2:"img/anna.png",
phrases:["Notre amour est comme un hivernage, il résiste aux tempêtes et se renforce avec le temps",
"Lorsque les jours raccourcissent et que le froid s'installe, notre amour brille comme une lueur d'espoir dans l'hivernage",
"Notre amour est comme un refuge chaleureux dans l'hivernage, un endroit où nous pouvons nous réfugier des tempêtes de la vie",
"Dans l'hivernage, notre amour continue de briller comme une étoile dans le ciel, résistant à toutes les intempéries",
"Notre amour est comme un feu de cheminée dans l'hivernage, une source de chaleur qui réchauffe nos coeurs",
"Dans l'hivernage, notre amour est comme un manteau doux et chaud qui nous protège du froid.",
"Notre amour est comme une fleur qui pousse dans la neige, un symbole de la beauté qui peut surgir même dans l'hivernage",
"Dans l'hivernage, notre amour est comme une lumière qui éclaire notre chemin, nous guidant à travers les moments difficiles",
"Notre amour est comme un arbre qui résiste aux intempéries de l'hivernage, grandissant en force et en beauté",
"Dans l'hivernage, notre amour est comme une promesse de renouveau, de nouvelles possibilités qui émergent du froid et de l'obscurité",
"Notre amour est comme un baume qui guérit les blessures de l'hivernage, nous aidant à retrouver la joie et la paix intérieure",
"Dans l'hivernage, notre amour est comme une oasis de chaleur et de réconfort, un endroit où nous pouvons nous reposer et nous ressourcer",
"Notre amour est comme un feu d'artifice dans l'hivernage, une explosion de couleurs et de lumière qui illumine notre vie",
"Dans l'hivernage, notre amour est comme une danse enivrante, nous faisant tourbillonner au rythme de nos coeurs",
"Notre amour est comme un livre que nous lisons ensemble dans l'hivernage, découvrant chaque page avec émerveillement",
"Dans l'hivernage, notre amour est comme un vin chaud qui réchauffe nos âmes, nous faisant oublier les rigueurs de l'hiver",
"Notre amour est comme un phare dans l'hivernage, nous guidant vers la sécurité et la lumière",
"Dans l'hivernage, notre amour est comme une prière silencieuse, nous aidant à trouver la paix et la sérénité dans les moments difficiles"]},
{nom:"lambiner",
prota1:"img/homer.png",
prota2:"img/marge.png",
phrases:["Avec toi, je pourrais lambiner toute une journée sans m'en lasser, tant j'aime ta compagnie",
"Lorsque je suis avec toi, le temps semble ralentir et je suis heureux de lambiner à tes côtés",
"J'aime lambiner avec toi, car chaque moment passé ensemble est un moment de bonheur",
"Lambiner avec toi est l'une de mes activités préférées, car tu m'apportes un calme et une sérénité incomparables",
"Lorsque je suis avec toi, je n'ai pas envie de faire autre chose que lambiner et profiter de ta présence",
"Lambiner avec toi est l'une de mes passions, car je sais que chaque moment passé ensemble est un moment précieux",
"Je pourrais lambiner toute une vie à tes côtés, car ta présence m'apporte une joie infinie",
"Lorsque je suis avec toi, le temps semble s'arrêter et je peux lambiner sans culpabilité, car tu m'apportes un réel bien-être",
"Je ne me lasserai jamais de lambiner avec toi, car chaque moment passé ensemble est unique et précieux",
"Lambiner avec toi est ma façon préférée de passer le temps, car je me sens heureux et en paix avec toi",
"Je suis tellement heureux de lambiner avec toi, car tu m'apportes une joie immense et un réel bonheur",
"Lambiner avec toi est l'une de mes activités préférées, car j'adore la manière dont tu rends chaque moment spécial",
"Je ne m'ennuie jamais lorsque je lambine avec toi, car ta présence m'apporte une satisfaction totale",
"Lambiner avec toi est l'une de mes activités préférées, car je peux me détendre complètement en ta compagnie",
"Lorsque je suis avec toi, je pourrais lambiner indéfiniment, car ta présence est tellement apaisante et réconfortante",
"Je suis tellement heureux de passer du temps avec toi, même si cela signifie simplement lambiner ensemble sans rien faire",
"Lambiner avec toi est l'un de mes moments préférés de la journée, car je peux simplement profiter de ta présence",
"Je ne me lasse jamais de lambiner avec toi, car chaque moment passé ensemble est une bénédiction",
"Lorsque je suis avec toi, je ne veux pas faire autre chose que lambiner, car tu m'apportes une joie immense",
"Je suis tellement heureux de lambiner avec toi, car ta présence est tellement précieuse pour moi"]},
{nom:"plusqueparfait",
prota1:"img/superman.png",
prota2:"img/lois.png",
phrases:["Je me souviens de notre amour plus-que-parfait, où chaque moment passé ensemble était une perfection inoubliable",
"Notre amour plus-que-parfait est une histoire que je raconterai encore et encore, car il n'y a rien de plus beau que l'amour que nous avons partagé",
"Lorsque je pense à notre amour plus-que-parfait, je me sens reconnaissant pour chaque moment que nous avons partagé ensemble",
"Notre amour plus-que-parfait était tellement intense que même le temps ne peut effacer les souvenirs de notre amour",
"Je chéris notre amour plus-que-parfait, car il a été l'une des plus belles choses que j'ai vécues dans ma vie",
"Notre amour plus-que-parfait était tellement fort que même les épreuves de la vie ne pouvaient pas nous séparer",
"Je suis tellement reconnaissant pour notre amour plus-que-parfait, car il m'a appris ce que c'est que d'aimer vraiment quelqu'un",
"Notre amour plus-que-parfait était tellement puissant que même la distance ne pouvait pas nous séparer",
"Je ne pourrai jamais oublier notre amour plus-que-parfait, car chaque moment passé avec toi était un moment de bonheur absolu",
"Notre amour plus-que-parfait est un souvenir que je chérirai toujours, car il a été l'un des plus beaux moments de ma vie",
"Notre amour plus-que-parfait était tellement fort que même les années n'ont pas réussi à effacer les souvenirs de notre amour",
"Je suis reconnaissant pour chaque moment passé avec toi, où notre amour était plus-que-parfait",
"Notre amour plus-que-parfait était un rêve devenu réalité, et je ne pourrais jamais être plus reconnaissant pour cela",
"Notre amour plus-que-parfait était tellement beau que même les mots ne peuvent pas décrire la profondeur de nos sentiments",
"Je suis tellement heureux que nous ayons eu notre amour plus-que-parfait, car cela a changé ma vie pour toujours",
"Notre amour plus-que-parfait était une expérience qui a illuminé ma vie et qui restera gravée dans mon coeur pour toujours",
"Notre amour plus-que-parfait était tellement intense que même maintenant, des années plus tard, je ressens toujours la même émotion en y pensant",
"Je suis reconnaissant pour notre amour plus-que-parfait, car il m'a appris à aimer et à être aimé de la meilleure façon possible",
"Notre amour plus-que-parfait était tellement fort que même la fin de notre relation n'a pas réussi à effacer les souvenirs de notre amour"]},
{nom:"rythmer",
prota1:"img/jayz.png",
prota2:"img/beyonce.png",
phrases:["Notre amour rythme ma vie, chaque battement de mon coeur résonne avec toi",
"Tu es la musique qui rythme ma vie, l'harmonie qui apaise mon âme, l'amour qui remplit mon coeur",
"L'amour rythme chaque moment de notre vie, chaque battement de notre coeur, chaque souffle que nous prenons ensemble",
"Notre amour rythme le temps, chaque instant passé ensemble est une symphonie de bonheur",
"Tu es le rythme de ma vie, l'amour qui me guide, la force qui me soutient",
"Notre amour rythme chaque seconde, chaque minute, chaque heure de notre vie",
"Tu rythmes mes pensées, mes rêves, mes espoirs, mon coeur bat pour toi",
"Notre amour est une danse enivrante, un rythme qui ne cesse de s'accélérer, un tourbillon d'émotions",
"Tu es la mélodie qui rythme ma vie, la note parfaite qui comble mon âme",
"Notre amour rythme le monde, chaque jour est une nouvelle chanson à écrire ensemble",
"Tu rythmes ma vie, mon coeur, mon âme, je ne peux pas imaginer une seconde sans toi",
"Notre amour rythme le silence, chaque regard échangé est une note douce et mélodieuse",
"Tu es l'amour qui rythme ma vie, la personne qui donne un sens à mes jours",
"Notre amour est comme une symphonie, chaque note est parfaitement accordée, chaque rythme est en harmonie avec l'autre",
"Tu rythmes mes pas, mes mouvements, ma vie entière, je ne peux pas me passer de toi",
"Notre amour rythme chaque saison, chaque changement de temps est une nouvelle occasion de célébrer notre amour",
"Tu es le rythme de mon coeur, la personne qui me donne la force de continuer à avancer",
"Notre amour est une chanson qui ne cesse de s'amplifier, une mélodie qui ne cesse de nous enchanter",
"Tu rythmes mes émotions, mes sentiments, tu es l'essence même de mon être",
"Notre amour rythme chaque battement de notre coeur, chaque instant de notre vie",
"Tu es la musique qui rythme ma vie, le son qui berce mon âme, l'amour qui m'envahit",
"Notre amour est un rythme continu, un battement de coeur qui ne cesse de s'amplifier"]},
{nom:"synchrone",
prota1:"img/red.png",
prota2:"img/pink.png",
phrases:["Notre amour est si synchrone que même les battements de nos coeurs se confondent",
"Tu es mon âme soeur, nous sommes synchrone, notre amour est comme une danse parfaite",
"Notre amour est synchrone, nos pensées se rencontrent, nos coeurs battent à l'unisson",
"Notre amour est synchrone, comme si nous avions été créés pour être ensemble",
"Tu es l'amour synchrone de ma vie, la personne qui me comprend sans même que j'ai besoin de parler",
"Notre amour est synchrone, nos vies s'entrelacent, nos coeurs ne font qu'un",
"Tu es le partenaire synchrone de ma vie, celui avec qui je veux danser pour toujours",
"Notre amour est synchrone, nous sommes en phase, notre relation est comme un orchestre qui joue une mélodie parfaite",
"Tu es la personne synchrone de ma vie, celle avec qui je veux marcher sur le même chemin",
"Notre amour est synchrone, nous sommes deux corps mais un seul esprit, une seule âme",
"Tu es l'amour synchrone de mon coeur, la personne qui sait comment me faire sourire",
"Notre amour est synchrone, nous avons trouvé la même cadence, la même mélodie",
"Tu es la personne synchrone de ma vie, celle qui a fait battre mon coeur à nouveau",
"Notre amour est synchrone, nos coeurs battent à l'unisson, notre amour ne connaît pas de limites",
"Tu es l'amour synchrone de mon âme, la personne qui me rend complet",
"Notre amour est synchrone, comme si nous avions été créés pour être ensemble, pour nous compléter",
"Tu es la personne synchrone de ma vie, celle avec qui je veux partager tous les moments",
"Notre amour est synchrone, nos vies s'harmonisent parfaitement, comme deux notes de musique",
"Tu es l'amour synchrone de mon coeur, la personne qui a fait de ma vie un conte de fées",
"Notre amour est synchrone, comme si nos destins étaient liés depuis toujours",
"Tu es la personne synchrone de ma vie, celle avec qui je veux construire un avenir ensemble",
"Notre amour est synchrone, nos coeurs battent à la même fréquence, notre amour ne peut que grandir",
"Tu es l'amour synchrone de mon âme, la personne qui me rend heureux chaque jour"]},
{nom:"tictac",
prota1:"img/joker.png",
prota2:"img/harley.png",
phrases:["Notre amour est comme une horloge, qui bat au rythme du tic-tac, toujours présent, toujours fidèle",
"Le tic-tac de mon coeur ne peut être arrêté, depuis que j'ai rencontré l'amour de ma vie",
"Tu es la raison du tic-tac de mon coeur, la personne qui donne un sens à ma vie",
"Notre amour est comme le tic-tac d'une horloge, régulier et constant, jamais en retard ni en avance",
"Le tic-tac de mon coeur est un rappel constant de mon amour pour toi, qui ne faiblit jamais",
"Notre amour est comme une horloge, qui bat au rythme du tic-tac, nous reliant à jamais",
"Le tic-tac de mon coeur est la preuve que mon amour pour toi est vrai et sincère",
"Notre amour est comme le tic-tac d'une horloge, chaque seconde nous rapprochant davantage l'un de l'autre",
"Le tic-tac de mon coeur est la musique de notre amour, une mélodie douce et constante qui ne s'arrête jamais",
"Notre amour est comme une horloge, dont le tic-tac me rappelle sans cesse à quel point je suis chanceux de t'avoir",
"Le tic-tac de mon coeur ne peut être interrompu, car mon amour pour toi est indestructible",
"Notre amour est comme le tic-tac d'une horloge, toujours en mouvement, toujours avançant vers un avenir radieux",
"Le tic-tac de mon coeur ne connaît qu'une seule direction, celle qui me mène tout droit vers toi",
"Notre amour est comme une horloge, dont le tic-tac rythme notre vie, nous rappelant que chaque instant est précieux",
"Le tic-tac de mon coeur est la preuve de l'intensité de mon amour pour toi, qui ne cesse de croître jour après jour",
"Notre amour est comme le tic-tac d'une horloge, qui ne peut être altéré par le temps ni par les épreuves de la vie",
"Le tic-tac de mon coeur est une symphonie d'amour pour toi, la personne la plus importante de ma vie",
"Notre amour est comme une horloge, dont le tic-tac ne connaît pas de frontières ni de limites",
"Le tic-tac de mon coeur est une promesse de mon amour éternel pour toi, qui ne disparaîtra jamais",
"Notre amour est comme le tic-tac d'une horloge, qui résonne à travers le temps et l'espace, jusqu'à l'infini"]}]